-- ============================================================
-- Supabase Database Schema — Portfolio Website
-- PostgreSQL Schema Blueprint
-- ============================================================

-- 1. Create Profile Settings Table (Single Record)
CREATE TABLE profile_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name VARCHAR(255) NOT NULL,
  job_title VARCHAR(255) NOT NULL,
  bio_summary TEXT NOT NULL,
  cv_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Contact Channels Table
CREATE TABLE contact_channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_name VARCHAR(100) NOT NULL,
  channel_value TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

-- 3. Create Skills Table
CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL,
  skill_tags TEXT[] DEFAULT '{}',
  sort_order INTEGER DEFAULT 0 NOT NULL
);

-- 4. Create Projects Table
CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  project_type VARCHAR(100) NOT NULL,
  tags TEXT[] DEFAULT '{}',
  live_url TEXT,
  store_url TEXT,
  is_visible BOOLEAN DEFAULT TRUE NOT NULL,
  is_featured BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at DATE
);

-- 5. Create Project Media Table (For Grid Carousel & Videos)
CREATE TABLE project_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  media_url TEXT NOT NULL,
  media_type VARCHAR(50) NOT NULL CHECK (media_type IN ('image', 'video')),
  sort_order INTEGER DEFAULT 0 NOT NULL
);

-- ============================================================
-- Enable Row Level Security on ALL Tables
-- ============================================================

ALTER TABLE profile_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_media ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS Policies — Public Read / Admin Write
-- ============================================================

-- Profile Settings: Public Read
CREATE POLICY "Allow public read access" ON profile_settings
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON profile_settings
  FOR ALL TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Contact Channels: Public Read (active only)
CREATE POLICY "Allow public read access" ON contact_channels
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON contact_channels
  FOR ALL TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Skills: Public Read
CREATE POLICY "Allow public read access" ON skills
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON skills
  FOR ALL TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Projects: Public Read (visible only)
CREATE POLICY "Allow public read access" ON projects
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON projects
  FOR ALL TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Project Media: Public Read
CREATE POLICY "Allow public read access" ON project_media
  FOR SELECT USING (true);

CREATE POLICY "Allow admin write access" ON project_media
  FOR ALL TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ============================================================
-- Insert Default Data
-- ============================================================

-- Default Profile
INSERT INTO profile_settings (full_name, job_title, bio_summary)
VALUES ('اسمك الكريم', 'مطور تطبيقات ويب وجوال', 'مرحباً بك في موقعي الشخصي — الموجه بالكامل بالبيانات.');

-- Default Contact Channels
INSERT INTO contact_channels (channel_name, channel_value, is_active) VALUES
  ('WhatsApp', '+967700000000', true),
  ('Email', 'your-email@example.com', true),
  ('Phone', '+967700000000', true);

-- Default Skills
INSERT INTO skills (skill_name, category, skill_tags, sort_order) VALUES
  ('React', 'فرونت إند', '{"JavaScript", "JSX", "Hooks"}', 1),
  ('Next.js', 'فرونت إند', '{"SSR", "App Router", "TypeScript"}', 2),
  ('Tailwind CSS', 'فرونت إند', '{"Utility-First", "Responsive"}', 3),
  ('Flutter', 'تطبيقات جوال', '{"Dart", "BLoC", "Cross-Platform"}', 4),
  ('TypeScript', 'أدوات تطوير', '{"Static Typing", "ES6+"}', 5),
  ('Supabase', 'باك إند', '{"PostgreSQL", "Auth", "Storage"}', 6);

-- Default Projects
INSERT INTO projects (title, description, project_type, tags, is_visible, is_featured) VALUES
  ('تطبيق إدارة المهام', 'تطبيق جوال متكامل لإدارة المهام والمشاريع اليومية مع واجهة مستخدم حديثة وسلسة.', 'mobile_app', '{"Flutter", "Dart", "BLoC", "Firebase"}', true, true),
  ('منصة التجارة الإلكترونية', 'موقع ويب متكامل للتجارة الإلكترونية مع نظام دفع آمن ولوحة تحكم إدارية.', 'web_app', '{"Next.js", "TypeScript", "Tailwind", "Stripe"}', true, true),
  ('تطبيق التتبع الصحي', 'تطبيق جوال لتتبع النشاط البدني والحمية الغذائية اليومية.', 'mobile_app', '{"Flutter", "Dart", "Provider"}', true, true);
